# --- Servicios ---
services:
  # --- PostgreSQL ---
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pfo3db
      POSTGRES_USER: pfo3user
      POSTGRES_PASSWORD: pfo3pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pfo3user -d pfo3db"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  # --- Adminer ---
  adminer:
    image: adminer:4
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

# --- Volúmenes ---
volumes:
  pgdata: